version: "3.8"

services:
  backend:
    build:
      context: backend-challenge
      dockerfile: /src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
  frontend:
    build:
      context: frontend-challenge
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-challenge:/app
      - /app/node_modules
  frontend-ang:
    build:
      context: frontend-challengeAng
      dockerfile: Dockerfile
    ports:
      - "4200:80"

    